### ISSUE TITLE
Provide more examples in API documentation comments

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumLibraries#113] opened 2019-05-24 21:07 UTC
In general, the API documentation pages for the Q# libraries are fairly light on examples. Adding more `/// # Example` sections would help make the libraries more accessible and easier to use.

**Comment by guenp** [comment] 2020-11-23 17:24
This is a good idea but the issue is a bit too general for us to actually get started on this.
My suggestions for action items:

- [ ] Create a new issue to add examples to one or two frequently used namespaces
- [ ] Explicitly make examples part of the Q# Libraries API proposal template.
- [ ] Close this issue

Tagging @cgranade @msoeken

**Comment by guenp** [comment] 2020-11-23 17:30
Interesting find when @msoeken were looking into the docs: https://github.com/MicrosoftDocs/quantum-docs-pr/issues/1121

**Comment by msoeken** [comment] 2022-04-27 22:16
Closing as duplicate to #339

**Closed by msoeken** 2022-04-27 22:16 UTC
Labels: Kind-Enhancement, Area-Documentation
